tough: Prepare for 1.13.1 tough release
awslabs/tough pull request #592
Opened 2023-03-20 23:58 UTC by ecpullen

*Issue #, if available:*
N/A

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-20 23:59 UTC, jpculp approved these changes

2023-03-21 00:31 UTC, stmcginnis approved these changes

2023-03-21 19:09 UTC, etungsten requested changes
Need to include https://github.com/awslabs/tough/pull/593 once it's merged

2023-03-21 19:42 UTC, webern commented
Can you change the PR name to `0.13.1`?

2023-06-01 17:56 UTC, jpculp commented
We might want to just scrap this and go **0.14.0** with the new AWS SDK for Rust updates.

2023-08-22 00:18 UTC, closed without merging