tough: Add 1 sec tolerance to system_time
awslabs/tough pull request #593
Opened 2023-03-21 17:30 UTC by ecpullen

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-21 17:34 UTC, jpculp approved these changes

2023-03-21 17:42 UTC, stmcginnis approved these changes
Seems like a safe thing to do.

2023-03-21 17:48 UTC, etungsten approved these changes

2023-03-21 19:49 UTC, webern requested changes
don't merge this yet please

2023-06-21 15:02 UTC, stmcginnis commented
> don't merge this yet please

Are we still waiting on something here?

2023-06-21 17:16 UTC, webern commented
> don't merge this yet please

We talked about it, but I don't remember what we decided. It feels very arbitrary to me. Either we allow the system time to change, or we don't... but 1 second?

2023-08-22 00:18 UTC, closed without merging